### ISSUE TITLE
Hub - `void` may be a better option than `null` for events with no data

### ISSUE THREAD

**Issue by manueliglesias** [elorzafe/amplify-types#15]
TypeScript support for custom Hub channels - Proposed Usage (v6)

https://github.com/elorzafe/amplify-types/blob/5cf2907add6065970bc435d146b907e20d2958c7/RFC%20Draft.md#L83-L90

https://github.com/elorzafe/amplify-types/blob/5cf2907add6065970bc435d146b907e20d2958c7/types/core.ts#L107-L109

The usage of `null` looks a little strange to me, e.g. why not `undefined` or `void` or even `never`?

`void` may be a better option than `null` for events with no data

![image](https://user-images.githubusercontent.com/6154160/225087417-4eb2079a-643b-4e8f-bd82-dcdced665f6a.png)

**Comment by jimblanc** [comment]
Incorporated feedback, thanks!
