### ISSUE TITLE
make use of `// @ts-expect-error` to show errors

### ISSUE THREAD

**Issue by manueliglesias** [elorzafe/amplify-types#16]
In the RFC make use of `// @ts-expect-error` so readers know that a certain line is expected to be an error, e.g.:

```typescript
      case 'C':
        // Type C doesn't have any associated event data
        // @ts-expect-error
        data = payload.data;
        break;
```

From https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments:

> When a line is preceded by a // @ts-expect-error comment, TypeScript will suppress that error from being reported; but if there’s no error, TypeScript will report that // @ts-expect-error wasn’t necessary.

**Comment by jimblanc** [comment]
Incorporated feedback, thanks!
