### ISSUE TITLE
`StorageObjectReference` and `StoragePrefixReference` types

### ISSUE THREAD

**Issue by calebpollman** [elorzafe/amplify-types#22]
In the `Storage` category changes, looks like we are adding some new types:
```
In order to permit better interoperability between storage APIs we will introduce StorageObjectReference & StoragePrefixReference types to represent items in cloud storage. An example for copying an object from one access level to another is highlighted below.
```

Not seeing further explanation/definitions for `StorageObjectReference` or `StoragePrefixReference`. Maybe I'm missing something here?

**Comment by jimblanc** [comment]
Good points, the full types are available in the sandbox but I just updated the RFC to include the partial types before the examples.
